require_relative './config/environment'
require 'sinatra/activerecord/rake' # Imports rake commands for ActiveRecord e.g. rake db:migrate

desc "Start our app console"
task :console do
  Pry.start
end
